"""MLModels with providers

Revision ID: 652776d0cb7e
Revises: 6954f8e74b45
Create Date: 2025-05-06 14:10:35.447375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '652776d0cb7e'
down_revision: Union[str, None] = '6954f8e74b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_model', sa.Column('name', sa.String(), nullable=True))
    op.add_column('ml_model', sa.Column('provider_type', sa.String(), nullable=True))
    op.add_column('ml_model', sa.Column('provider_url', sa.String(), nullable=True))
    op.add_column('ml_model', sa.Column('provider_secret_key', sa.String(), nullable=True))
    op.add_column('ml_model', sa.Column('provider_submodel', sa.String(), nullable=True))
    op.add_column('ml_model', sa.Column('map50', sa.Float(), nullable=True))
    op.drop_constraint('ml_model_infection_id_fkey', 'ml_model', type_='foreignkey')
    op.drop_column('ml_model', 'algorithm')
    op.drop_column('ml_model', 'infection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_model', sa.Column('infection_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ml_model', sa.Column('algorithm', postgresql.ENUM('YOLO', 'ResNet', 'EfficientNet', 'DenseNet', 'MaskRCNN', 'DeepLab', 'ViT', 'Hybrid', 'ImageNet', 'UNet', name='algorithmenum'), autoincrement=False, nullable=False))
    op.create_foreign_key('ml_model_infection_id_fkey', 'ml_model', 'infection', ['infection_id'], ['id'])
    op.drop_column('ml_model', 'map50')
    op.drop_column('ml_model', 'provider_submodel')
    op.drop_column('ml_model', 'provider_secret_key')
    op.drop_column('ml_model', 'provider_url')
    op.drop_column('ml_model', 'provider_type')
    op.drop_column('ml_model', 'name')
    # ### end Alembic commands ###
