"""init

Revision ID: 6954f8e74b45
Revises: 
Create Date: 2025-05-05 11:08:21.104602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6954f8e74b45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_culture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plant_culture_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plant_culture_id'], ['plant_culture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('infection_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.Enum('YOLO', 'ResNet', 'EfficientNet', 'DenseNet', 'MaskRCNN', 'DeepLab', 'ViT', 'Hybrid', 'ImageNet', 'UNet', name='algorithmenum'), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('prediction', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['infection_id'], ['infection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ml_model_id', sa.Integer(), nullable=False),
    sa.Column('received_photo', sa.String(), nullable=False),
    sa.Column('marked_photo', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('coord', sa.String(), nullable=False),
    sa.Column('sectors_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ml_model_id'], ['ml_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('ml_model')
    op.drop_table('infection')
    op.drop_table('plant_culture')
    # ### end Alembic commands ###
